### ISSUE TITLE
Idea: Toggle which structures can appear.

### ISSUE THREAD

**Issue by Wolfie713** [TechnicJelle/BlueMapStructures#6]
Referring to issue #5.

In the config file, have a list of supported structures along with their setting.

```
# Choose how each type of structure is handled.
# Options include: plugin (plugin's internal value for the structure), global (use global setting), show, hide, ground (tries to limit based on visibility).
# The option for "global" only include plugin, show, hide, ground.
  structures:
    global: ground
    ocean_monument: show
    ruined_portal: global
    mineshaft: global
    desert_temple: plugin
    stronghold: plugin
    mansion: plugin
    ...
```

The "internal value" should be a planned out set of values that aim to hide structures that are generally hard to spot from regular above ground exploring, so that someone who doesn't want them too easily found isn't suddenly struggling with toggling them.  The default values should be "global=plugin" and all the others are set to global.  So all someone has to do is mess with the global setting to turn them all on or off (show/hide), but then can fine tune from there.  The "ground" setting, well, I'm hoping you have an easy way to figure out how to make that work.  If there isn't any easy way, then I guess using the sea level as the cutoff point (y=60 I think?) and the docs would just say that ground is considered to be 60+.

Ideally, people wouldn't need to change any of the settings, but for those who want to tweak them, they can.  So someone might decide to have ocean monuments shown while all ruined portals are hidden, for example.
